const scale = 5;

const distanceCoeff = 1 / 232.54;

const timeQuotient = 10000;

const firstTarget = "Soleil";

const diametreFormule = 1 / 12756;
const distanceFormule = 1 / 149600000;

const freeSpeedCoeff = .01;

const beginNavIndex = 0; // index de l'astre de départ pour la liste des destinations en navigation avec les flèches

const astres = [{
        name: "Soleil",
        icon: "Soleil.png",
        diametre: 109 * scale,
        distance: 0 * scale,
        texture: "sun.jpg",
        textureType: "emissive",
        godrays: true,
        positionDebut: Math.random() * 10000,
        angularOrbit: 0,
        angularSelf: 7.25,
        coeffrotation: 1 / 27,
        annee: 1000,
        satellites: "Toutes les planètes du système solaire",
        rotation: "27&nbsp;jours",
        revolution: "Négligable autour du barycentre",
        description: "Le Soleil est l'étoile de notre système solaire, il se situe en son centre et toutes les planètes orbitent autour de lui<span class='point'>.</span>"
    },
    {
        name: "Mercure",
        icon: "Mercure.png",
        diametre: 0.382 * scale,
        distance: (30 * 3) * scale,
        texture: "mercure.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        angularOrbit: 7.005,
        angularSelf: 0.0352,
        coeffrevolution: 4.2,
        coeffrotation: 1 / 58,
        annee: 88,
        satellites: 0,
        rotation: "58&nbsp;jours&nbsp;et&nbsp;16&nbsp;heures",
        revolution: "88&nbsp;jours (résonante 3/2)",
        description: "La planète la plus proche du soleil<span class='point'>.</span> De plus, Mercure tourne 3 fois sur elle même toutes les 2 révolutions autour du Soleil<span class='point'>.</span> On appelle cela la résonance orbitale<span class='point'>.</span>"
    },
    {
        name: "Vénus",
        icon: "Venus.png",
        diametre: .949 * scale,
        distance: 168.19 * scale,
        texture: "venus.jpg",
        textureType: "diffuse",
        positionDebut: getRandom(0, 1000),
        atm: {
            opacity: .3,
            texture: "black.png",
        },
        angularOrbit: 3.39,
        angularSelf: 177.36,
        coeffrevolution: 1.175,
        coeffrotation: .0041037952,
        annee: 224.7,
        satellites: 0,
        rotation: "243&nbsp;jours",
        revolution: "224,7&nbsp;jours",
        description: "La planète la plus chaude du système solaire du fait de son épaisse enveloppe de nuages qui provoque un immense effet de serre, en effet sa température est de 490°C au maximum<span class='point'>.</span> De plus, Vénus tourne d'est en ouest, à l'inverse de toutes les autres planètes du système solaire<span class='point'>.</span> Vénus est cependant surnommée \"La soeur jummelle de la Terre\" du fait de leur masse très semblable de même que leur taille<span class='point'>.</span> Vénus se situe dans la zone habitable du Soleil<span class='point'>.</span>"
    },
    {
        name: "La Terre",
        icon: "Terre.png",
        diametre: 1 * scale,
        distance: 232.54 * scale,
        texture: "earth.jpg",
        textureType: "diffuse",
        specular: "specular.jpg",
        emissive: "night2.jpg",
        positionDebut: 10000,
        atm: {
            opacity: .4,
            texture: "clouds4.jpg",
        },
        angularOrbit: 0,
        angularSelf: 23.43,
        coeffrevolution: 1,
        coeffrotation: 1,
        annee: 365.25,
        satellites: 1,
        rotation: "23&nbsp;heures&nbsp;56&nbsp;minutes",
        revolution: "365,25&nbsp;jours",
        description: "La Terre est le seul astre de notre système solaire possédant de l'eau liquide à sa surface<span class='point'>.</span> La Terre est égalment la seule planète du système solaire à avoir vu se développer la vie et une civilisation intelligente<span class='point'>.</span>"
    },
    {
        name: "La Lune",
        icon: "Lune.png",
        diametre: 0.273 * scale,
        distance: 15 * scale,
        realdistance: 384000,
        texture: "moon.jpg",
        textureType: "diffuse",
        positionDebut: 0,
        parent: "La Terre",
        angularOrbit: 5.145,
        angularSelf: 6.687,
        coeffrevolution: 0,
        coeffrotation: 0,
        annee: 29.5,
        satellites: 0,
        rotation: "29,5&nbsp;jours&nbsp;(synchrone)",
        revolution: "29,5&nbsp;jours&nbsp;(synchrone)",
        description: "La Lune est le compagnon inséparable de la Terre<span class='point'>.</span> La Lune s'est formée, dit-on, de l'impact d'une planète avec la Terre lors de la formation du système solaire, une partie des débris auraient alors formé la Lune<span class='point'>.</span> Le Satellite de la Terre est responsable des marées et du ralentissement de la vitesse de rotation de la Terre sur elle même<span class='point'>.</span> La Lune est seul astre à ce jour à avoir été foulé par l'Homme avec la Terre bien sûr<span class='point'>.</span>"
    },
    {
        name: "Mars",
        icon: "Mars.png",
        diametre: 0.532 * scale,
        distance: 354.4 * scale,
        texture: "mars.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        atm: {
            opacity: .2,
            texture: "black.png",
        },
        angularOrbit: 1.8506,
        angularSelf: 25.19,
        coeffrevolution: 0.811,
        coeffrotation: 0.972899729,
        annee: 686,
        satellites: 2,
        rotation: "24&nbsp;heures&nbsp;36&nbsp;minutes",
        revolution: "686&nbsp;jours",
        description: "Surnommée \"La Planète Rouge\", Mars est la dernière planète tellurique de notre système solaire<span class='point'>.</span> Mars a presque entièrement perdu son atmosphère du fait de l'absence de champ magnétique, mais les scientifiques pensent que Mars a pu abriter de l'eau liquide et donc potentiellement de la vie à une époque lointaine<span class='point'>.</span>"
    },
    {
        name: "Jupiter",
        icon: "Jupiter.png",
        diametre: 11 * scale,
        distance: 1209.79 * scale,
        texture: "jupiter.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        atm: {
            opacity: .4,
            texture: "black.png",
        },
        angularOrbit: 1.304,
        angularSelf: 3.12,
        coeffrevolution: 0.043,
        coeffrotation: 2.4338983051,
        annee: 11 * 365.25 + 314,
        satellites: 69,
        rotation: "9&nbsp;heures&nbsp;30&nbsp;minutes",
        revolution: "11&nbsp;ans&nbsp;314&nbsp;jours",
        description: "Jupiter est la plus grande de toutes les planètes de notre système solaire (11X plus grande que la Terre)<span class='point'>.</span> Il s'agit de la première des planètes gazeuses<br/>Son apparence est dûe à la présence de différents gaz colorés et de vents supersoniques dans son atmosphère<span class='point'>.</span>"
    },
    {
        name: "Io",
        icon: "Io.png",
        diametre: 0.31185 * scale,
        distance: 30 * scale,
        realdistance: 421800,
        texture: "io.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        parent: "Jupiter",
        angularOrbit: 0.036 + 3.12,
        angularSelf: 0,
        coeffrevolution: 0,
        coeffrotation: 0,
        annee: 1.769,
        satellites: 0,
        rotation: "1,769 jours&nbsp;(synchrone)",
        revolution: "1,769&nbsp;jours&nbsp;(synchrone)",
        description: "Io est un des quatre satellites Galiléens (satellites les plus gros de Jupiter)<span class='point'>.</span> Io est également l'astre le plus actif du système solaire avec 400 volcans en activité<span class='point'>.</span> Cette forte activitée est due aux puissantes forces de marées de Jupiter sur Io<span class='point'>.</span>"
    },
    {
        name: "Europe",
        icon: "Europe.png",
        diametre: 1 * scale / (12756 / 3121.6),
        distance: 50 * scale,
        realdistance: 671100,
        texture: "europe.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        parent: "Jupiter",
        angularOrbit: 0.469 + 3.12,
        angularSelf: 0,
        coeffrevolution: 0,
        coeffrotation: 0,
        annee: 3.551181,
        satellites: 0,
        rotation: "3,55 jours&nbsp;(synchrone)",
        revolution: "3,55&nbsp;jours&nbsp;(synchrone)",
        description: "Europe est le deuxième satellite Galiléen<span class='point'>.</span> Son enveloppe de glace abrite un océan souterrain et donc peut-être de la vie<span class='point'>.</span>"
    },
    {
        name: "Ganymède",
        icon: "Ganymede.png",
        diametre: 1 * scale / (12756 / 5262.4),
        distance: 80 * scale,
        realdistance: 1070400,
        texture: "ganymede.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        parent: "Jupiter",
        angularOrbit: 0.21 + 3.12,
        angularSelf: 0,
        coeffrevolution: 0,
        coeffrotation: 0,
        annee: 7.15,
        satellites: 0,
        rotation: "7,15 jours&nbsp;(synchrone)",
        revolution: "7,15&nbsp;jours&nbsp;(synchrone)",
        description: "Ganymède est le troisième satellite Galiléen, il est le plus gros de tous les satellites du système solaire et est le seul a posséder une magnétosphère<span class='point'>.</span>"
    },
    {
        name: "Callisto",
        icon: "Callisto.png",
        diametre: 1 * scale / (12756 / 4820),
        distance: 150 * scale,
        realdistance: 1882700,
        texture: "callisto.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        parent: "Jupiter",
        angularOrbit: 0.192 + 3.12,
        angularSelf: 0,
        coeffrevolution: 0,
        coeffrotation: 0,
        annee: 16.68,
        satellites: 0,
        rotation: "16,68 jours&nbsp;(synchrone)",
        revolution: "16,68&nbsp;jours&nbsp;(synchrone)",
        description: "Callisto est le quatrième et dernier satellite Galiléen<span class='point'>.</span> Comme Europe, Callisto possède un océan, environ 100km sous sa surface, et donc potentiellement de la vie"
    },
    {
        name: "Saturne",
        icon: "Saturne.png",
        diametre: 9 * scale,
        distance: 2218.13 * scale,
        texture: "saturn.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        atm: {
            opacity: .4,
            texture: "black.png",
        },
        angularOrbit: 2.4845,
        angularSelf: 26.73,
        rings: {
            texture: "rings.png",
            size: 20,
            alpha: 0.5
        },
        coeffrevolution: 0.0323,
        coeffrotation: 2.338762215,
        annee: 29 * 365.25 + 167,
        satellites: 62,
        rotation: "10&nbsp;heures&nbsp;14&nbsp;minutes",
        revolution: "29&nbsp;ans&nbsp;167&nbsp;jours",
        description: "Saturne est la seconde plus grande planète de notre système solaire<span class='point'>.</span> Elle se distingue de toutes les autres par la présence de ses immenses anneaux de roches et de glaces<span class='point'>.</span>"
    },
    {
        name: "Mimas",
        icon: "Mimas.png",
        diametre: 1 * scale / (12756 / 400),
        distance: 15 * scale,
        realdistance: 185520,
        texture: "mimas.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        parent: "Saturne",
        angularOrbit: 1.566 + 26.73,
        angularSelf: 0,
        coeffrevolution: 0.001,
        coeffrotation: 0,
        annee: 0.942,
        satellites: 0,
        rotation: "0,942 jours&nbsp;(synchrone)",
        revolution: "0,942&nbsp;jours&nbsp;(synchrone)",
        description: "Mimas est le plus petit satellite sphéroïde de Saturne, il en est également le plus proche<span class='point'>.</span> Sa surface est marquée par un cratère géant de 130km de diamètre nommé cratère de Hershel du nom de l'astronome qui découvrit Mimas en 1789<span class='point'>.</span>"
    },
    {
        name: "Encelade",
        icon: "Encelade.png",
        diametre: 1 * scale / (12756 / 504),
        distance: 30 * scale,
        realdistance: 238020,
        texture: "encelade.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        parent: "Saturne",
        angularOrbit: 0.019 + 26.73,
        angularSelf: 0,
        coeffrevolution: 0.001,
        coeffrotation: 0,
        annee: 1.37,
        satellites: 0,
        rotation: "1,37 jours&nbsp;(synchrone)",
        revolution: "1,37&nbsp;jours&nbsp;(synchrone)",
        description: "Satellite gelé de Saturne, Encelade est pourtant très active, comme l'indique la présence de geysers d'eau carbonnée à sa surface<span class='point'>.</span> Cela indique la présence d'un océan souterrain et pourquoi pas de la vie<span class='point'>.</span>"
    },
    {
        name: "Téthys",
        icon: "Tethys.png",
        diametre: 1 * scale / (12756 / 1060),
        distance: 45 * scale,
        realdistance: 294619,
        texture: "tethys.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        parent: "Saturne",
        angularOrbit: 0.168 + 26.73,
        angularSelf: 0,
        coeffrevolution: 0.001,
        coeffrotation: 0,
        annee: 1.88,
        satellites: 0,
        rotation: "1,88 jours&nbsp;(synchrone)",
        revolution: "1,88&nbsp;jours&nbsp;(synchrone)",
        description: "Téthys est un satellite de Saturne qui a la particularité d'avoir une densité très proche de celle de l'eau, ce qui trahit la présence de glace sur le satellite<span class='point'>.</span>"
    },
    {
        name: "Dioné",
        icon: "Dione.png",
        diametre: 1 * scale / (12756 / 1118),
        distance: 60 * scale,
        realdistance: 377420,
        texture: "dione.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        parent: "Saturne",
        angularOrbit: 0.002 + 26.73,
        angularSelf: 0,
        coeffrevolution: 0.001,
        coeffrotation: 0,
        annee: 2.737,
        satellites: 0,
        rotation: "2,737 jours&nbsp;(synchrone)",
        revolution: "2,737&nbsp;jours&nbsp;(synchrone)",
        description: "Dioné est un satellite composé essentiellment de glace, cependant, sa densité plus élevée laisse pensée que Dioné est composé également de roches de silicates<span class='point'>.</span>"
    },
    {
        name: "Rhéa",
        icon: "Rhea.png",
        diametre: 1 * scale / (12756 / 1529),
        distance: 70 * scale,
        realdistance: 527070,
        texture: "rhea.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        parent: "Saturne",
        angularOrbit: 0.331 + 26.73,
        angularSelf: 0,
        coeffrevolution: 0.001,
        coeffrotation: 0,
        annee: 4.518,
        satellites: 0,
        rotation: "4,518 jours&nbsp;(synchrone)",
        revolution: "4,518&nbsp;jours&nbsp;(synchrone)",
        description: "Rhéa est le second plus gros satellite de Saturne<span class='point'>.</span> De plus, dans le passé, Rhéa était un satellite possédant des volcans gelés très actifs<span class='point'>.</span>"
    },
    {
        name: "Titan",
        icon: "Titan.png",
        diametre: 0.404 * scale,
        distance: 100 * scale,
        realdistance: 1221870,
        texture: "titan.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        parent: "Saturne",
        atm: {
            opacity: .2,
            texture: "black.png"
        },
        angularOrbit: 0.280 + 26.73,
        angularSelf: 0,
        coeffrevolution: 0.001,
        coeffrotation: 0,
        annee: 15.95,
        satellites: 0,
        rotation: "15,95 jours&nbsp;(synchrone)",
        revolution: "15,95&nbsp;jours&nbsp;(synchrone)",
        description: "Un des satellites de Saturne le plus connu, et le plus gros aussi<span class='point'>.</span> Il a la particularité de posséder une athmosphère et d'être couvert de mers de méthane liquide à sa surface<span class='point'>.</span>"
    },
    {
        name: "Japet",
        icon: "Japet.png",
        diametre: 1 * scale / (12756 / 1460),
        distance: 120 * scale,
        realdistance: 3560840,
        texture: "japet.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        parent: "Saturne",
        angularOrbit: 7.489 + 26.73,
        angularSelf: 0,
        coeffrevolution: 0.001,
        coeffrotation: 0,
        annee: 79.33,
        satellites: 0,
        rotation: "79,33 jours&nbsp;(synchrone)",
        revolution: "79,33&nbsp;jours&nbsp;(synchrone)",
        description: "Satellite de Saturne possédant une coloration différente entre son hémisphère nord et son hémisphère sud<span class='point'>.</span> De plus, Japet possède une crête équatoriale haute de 10km<span class='point'>.</span>"
    },
    {
        name: "Uranus",
        icon: "Uranus.png",
        diametre: 4.007 * scale,
        distance: 4459.59 * scale,
        texture: "uranus.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        atm: {
            opacity: .4,
            texture: "black.png"
        },
        angularSelf: 97.8,
        angularOrbit: 0.7725,
        rings: {
            texture: "uranus_rings.png",
            size: 8,
            alpha: 0.7
        },
        coeffrevolution: 0.228,
        coeffrotation: 1.3914728682,
        annee: 84 * 365.25 + 7,
        satellites: 5,
        rotation: "17&nbsp;heures&nbsp;12&nbsp;minutes",
        revolution: "84&nbsp;ans&nbsp;7&nbsp;jours",
        description: "Uranus est l'avant dernière planète de notre sytème solaire<span class='point'>.</span> Sa particularité est son axe de rotation, qui donne l'impression que Uranus de rouler sur son orbite<span class='point'>.</span> Ses anneaux sont donc inclinés de la même manière<span class='point'>.</span>"
    },
    {
        name: "Miranda",
        icon: "Miranda.png",
        diametre: 1 * scale / (12756 / 470),
        distance: 15 * scale,
        realdistance: 129872,
        texture: "miranda.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        parent: "Uranus",
        angularOrbit: 97.8 + 4.338,
        angularSelf: 0,
        coeffrevolution: 0.001,
        coeffrotation: 0,
        annee: 1.41,
        satellites: 0,
        rotation: "1,41 jours&nbsp;(synchrone)",
        revolution: "1,41&nbsp;jours&nbsp;(synchrone)",
        description: "Satellite d'Uranus ayant la particularité de posséder un plan orbital perpendiculaire au plan du système solaire<span class='point'>.</span> Miranda est le satellite le plus petit et le plus proche d'Uranus<span class='point'>.</span>"
    },
    {
        name: "Ariel",
        icon: "Ariel.png",
        diametre: 1 * scale / (12756 / 1160),
        distance: 30 * scale,
        realdistance: 190900,
        texture: "ariel.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        parent: "Uranus",
        angularOrbit: 97.8 + 0.260,
        angularSelf: 0,
        coeffrevolution: 0.001,
        coeffrotation: 0,
        annee: 2.52,
        satellites: 0,
        rotation: "2,52 jours&nbsp;(synchrone)",
        revolution: "2,52&nbsp;jours&nbsp;(synchrone)",
        description: "Satellite d'Uranus ayant la particularité de posséder un plan orbital perpendiculaire au plan du système solaire<span class='point'>.</span> Ariel est la plus brillante des lunes d'Uranus<span class='point'>.</span>"
    },
    {
        name: "Umbriel",
        icon: "Umbriel.png",
        diametre: 1 * scale / (12756 / 1169),
        distance: 45 * scale,
        realdistance: 266300,
        texture: "umbriel.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        parent: "Uranus",
        angularOrbit: 97.8 + 0.128,
        angularSelf: 0,
        coeffrevolution: 0.001,
        coeffrotation: 0,
        annee: 4.144,
        satellites: 0,
        rotation: "4,144 jours&nbsp;(synchrone)",
        revolution: "4,144&nbsp;jours&nbsp;(synchrone)",
        description: "Satellite d'Uranus ayant la particularité de posséder un plan orbital perpendiculaire au plan du système solaire, de plus, Umbriel possède un noyau rocheux<span class='point'>.</span>"
    },
    {
        name: "Titania",
        icon: "Titania.png",
        diametre: 1 * scale / (12756 / 1578),
        distance: 60 * scale,
        realdistance: 436300,
        texture: "titania.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        parent: "Uranus",
        angularOrbit: 97.8 + 0.340,
        angularSelf: 0,
        coeffrevolution: 0.001,
        coeffrotation: 0,
        annee: 8.7,
        satellites: 0,
        rotation: "8,7 jours&nbsp;(synchrone)",
        revolution: "8,7&nbsp;jours&nbsp;(synchrone)",
        description: "Satellite d'Uranus ayant la particularité de posséder un plan orbital perpendiculaire au plan du système solaire<span class='point'>.</span> Titania est d'ailleurs le satellite le plus grand d'Uranus<span class='point'>.</span>"
    },
    {
        name: "Obéron",
        icon: "Oberon.png",
        diametre: 1 * scale / (12756 / 1523),
        distance: 75 * scale,
        realdistance: 583519,
        texture: "oberon.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        parent: "Uranus",
        angularOrbit: 97.8 + 0.058,
        angularSelf: 0,
        coeffrevolution: 0.001,
        coeffrotation: 0,
        annee: 13.46,
        satellites: 0,
        rotation: "13,46 jours&nbsp;(synchrone)",
        revolution: "13,46&nbsp;jours&nbsp;(synchrone)",
        description: "Satellite d'Uranus ayant la particularité de posséder un plan orbital perpendiculaire au plan du système solaire<span class='point'>.</span> Obéron est le satellite le plus éloigné d'Uranus<span class='point'>.</span>"
    },
    {
        name: "Neptune",
        icon: "Neptune.png",
        diametre: 3.883 * scale,
        distance: 6988.6 * scale,
        texture: "neptune.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        atm: {
            opacity: .4,
            texture: "black.png"
        },
        rings: {
            texture: "neptune_rings.png",
            size: 10,
            alpha: 0.7
        },
        angularOrbit: 1.7692,
        angularSelf: 29.58,
        coeffrevolution: 182,
        coeffrotation: 1.4865424431,
        annee: 164 * 365.25 + 280,
        satellites: 15,
        rotation: "16&nbsp;heures&nbsp;6&nbsp;minutes",
        revolution: "164&nbsp;ans&nbsp;280&nbsp;jours",
        description: "La dernière planète du système solaire<span class='point'>.</span> Elle est la planète qui met le plus de temps à accomplir une révolution autour du Soleil<span class='point'>.</span> En effet, elle met environ 164 ans à la faire<span class='point'>.</span>"
    },
    {
        name: "Protée",
        icon: "Protee.png",
        diametre: 1 * scale / (12756 / 420),
        distance: 20 * scale,
        realdistance: 117647,
        texture: "proteus.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        parent: "Neptune",
        angularOrbit: 0.026 + 29.58,
        angularSelf: 0,
        coeffrevolution: 0.001,
        coeffrotation: 0,
        annee: 1.122,
        satellites: 0,
        rotation: "1,122 jours&nbsp;(synchrone)",
        revolution: "1,122&nbsp;jours&nbsp;(synchrone)",
        description: "Un des satellites les plus sombre du système solaire : il ne réfléchit que 10% de la lumière du soleil<span class='point'>.</span>"
    },
    {
        name: "Triton",
        icon: "Triton.png",
        diametre: 1 * scale / (12756 / 2706),
        distance: 60 * scale,
        realdistance: 354759,
        texture: "triton.jpg",
        textureType: "diffuse",
        positionDebut: Math.random() * 10000,
        parent: "Neptune",
        angularOrbit: 156.865 + 29.58,
        angularSelf: 0,
        coeffrevolution: 0.001,
        coeffrotation: 0,
        annee: 5.877,
        satellites: 0,
        rotation: "5,877 jours&nbsp;(synchrone)",
        revolution: "5,877&nbsp;jours&nbsp;(synchrone)",
        description: "Le plus gros des satellites de Neptune<span class='point'>.</span> De plus, il possède une orbite rétrograde<span class='point'>.</span>"
    },
];

const belts = [{
    name: "ceintureAsteroides",
    yDivergence: 10 * scale,
    nb: 4000,
    size: 0.2,
    position: {
        nearest: 629.53 * scale,
        farthest: 746.11 * scale
    },
    parent: null,
    texture: "diffuse"
}];